aptible-cli:
  setup:
    docker:
      cache_keys:
        - Dockerfile
      docker_build:
        dockerfile: Dockerfile
        tag: gusto/aptible-cli-docker:$BUILDKITE_COMMIT
      artifacts:
        - name: gusto/aptible-cli-docker:$BUILDKITE_COMMIT
          type: docker
